version: '3.8'

services:
  backend:
    build:
      context: ./frontend_react
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./backend_flask
      dockerfile: Dockerfile
    ports:
      - "3000:80"
